
CREATE SEQUENCE SEQ_SNS_ACT_SCORE START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_AD_LINK START WITH 27 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_AD_POST_TAG START WITH 20 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_AD_TAG START WITH 9 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_AUTH_CODE START WITH 35 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_CATEGORY START WITH 8 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_COMMENTS START WITH 52 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_DM_MESSAGE START WITH 48 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_DM_ROOM START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_DM_ROOM_USER START WITH 21 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_FAVORITE_FOLDER START WITH 20 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_FAVORITE_PLACE START WITH 17 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_FOLLOW_REQUEST START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_FOLLOWS START WITH 23 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_NOTIFICATION START WITH 83 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_POST START WITH 96 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_POST_FILE START WITH 132 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_POST_LIKE START WITH 50 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_POST_TAG START WITH 289 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_REPORT START WITH 7 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_SEARCH_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_TAG START WITH 420 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_USER_ACT_LOG START WITH 213 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_USER_BLOCK START WITH 7 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_USER_INTR_SCORE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SNS_USER_NOTI_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
